DROP TABLE IF EXISTS patient_info;
CREATE TABLE patient_info (
id  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT ,
inpatient_no  TEXT(64) NOT NULL ,
name  TEXT(64) NOT NULL ,
sex  TEXT(5),
birthday  TEXT(64),
age  TEXT(5)  ,
department  TEXT(10)  ,
bed_no  TEXT(5)  ,
diagnosis  TEXT(1024)  ,
doctor_id  int(11) NOT NULL ,
doctor  TEXT(64) ,
create_time  TEXT(64) ,
update_time  TEXT(64)  ,
sync_flag  INTEGER  NOT NULL ,
sync_time  TEXT(64) 
);
DROP TABLE IF EXISTS archives_record;
CREATE TABLE archives_record (
id  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT ,
doctor_id  INTEGER NOT NULL ,
inpatient_no  TEXT(64),
record_time  TEXT(64) ,
bed  TEXT(45) ,
diagnosis  TEXT(45) ,
department  TEXT(45)  ,
is_operation  INTEGER ,
wound_type  INTEGER  ,
wound_height  REAL(10,2) ,
wound_width  REAL(10,2)  ,
wound_deep  REAL(10,2)  ,
wound_area  REAL(10,2) ,
wound_volume  REAL(10,2)  ,
wound_time  TEXT(64)  ,
wound_postion  INTEGER  ,
wound_postionx  INTEGER ,
wound_postiony  INTEGER  ,
wound_measures  INTEGER  ,
wound_describe_clean  INTEGER  ,
wound_color_red  REAL(10,2)  ,
wound_color_yellow  REAL(10,2)  ,
wound_color_black  REAL(10,2)  ,
wound_describe_color  INTEGER ,
wound_describe_skin  INTEGER  ,
wound_assess_prop  INTEGER ,
wound_assess_infect  INTEGER ,
wound_assess_infect_desc  TEXT(255) ,
wound_leachate_volume  INTEGER ,
wound_leachate_color  INTEGER ,
wound_leachate_smell  INTEGER ,
wound_heal_all  TEXT(255) ,
wound_heal_position  TEXT(255) ,
wound_doppler  TEXT(255) ,
wound_cta  TEXT(255) ,
wound_mr  TEXT(255) ,
wound_petct  TEXT(255) ,
wound_dressing  INTEGER ,
create_time  TEXT(64) ,
update_time  TEXT(64)  ,
sync_flag  INTEGER  NOT NULL ,
sync_time  TEXT(64) 
);